#!/usr/bin/env bash
declare username
declare pgpassword

function passn {
    < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-$1};echo;
}

if [[ ! -e $HOME/.pgdpassword ]]; then
  passn 12 > $HOME/.pgdpassword
fi
pgpassword=`cat $HOME/.pgdpassword`

psql postgres://`cat .pguser`@`cat .pghost`:`cat .pgport`/postgres <<EOF
CREATE USER diaspora WITH CREATEDB PASSWORD '$pgpassword';
EOF

curl -L https://s.diaspora.software/1t | bash

if grep -qv '$HOME/.rvm/scripts/rvm' .bashrc; then
  cat >> .bashrc <<'EOF'
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 
EOF
  source $HOME/.bashrc
fi

# Uncomment if your current user doesn't have the sudo privileges
# rvm autolibs read-fail

rvm install 2.4

# Get Diaspora source
git clone -b master https://github.com/diaspora/diaspora.git
pushd diaspora

if [[ ! -e config/database.yml ]]; then
  cp config/database.yml.example config/database.yml
fi
if [[ ! -e config/diaspora.yml ]]; then
  cp config/diaspora.yml.example config/diaspora.yml
fi

# Edit config/database.yml
#username Make sure to use the right username you created for diaspora.
#password Make sure to use the right password for the user your created for diaspora.
#host
# Edit config/diaspora.yml
#environment.url: Set the public facing URL to your pod here, for example for https://pod.geraspora.de this would be https://pod.geraspora.de
#environment.certificate_authorities: You have to set this, one of the examples should fit. If the file in the example doesn't exist you're missing a package, in most cases it's named ca-certificates.
#server.rails_environment: You must set this to production. The server section is read by ./script/server and most alternative startup methods to setup the correct environment.
#environment.require_ssl: If for some reason you can't run your pod on HTTPS (we highly encourage you to do it!), set this to false to prevent a redirect from http:// to https://

gem install bundler
script/configure_bundler
bin/bundle install --full-index

RAILS_ENV=production bin/rake db:create db:migrate
RAILS_ENV=production bin/rake assets:precompile

echo "`pwd`./script/server starts the server."
popd

# Nginx https://gist.github.com/1355430
#end
